// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceType } from "./DeviceType";
import type { OutboundPayload } from "./OutboundPayload";

export type SendInfo = { id: string, name: string, addr: string, device_type: DeviceType, ob: OutboundPayload, };
